import Link from 'next/link';
import type { ReactNode } from 'react';
import { ArrowUpRight, ExternalLink } from 'lucide-react';
import { PerksWordmark } from './perks-brand';

const nav=[['Overview','overview'],['Launching','launching'],['Trading rewards','rewards'],['Gift cards','gift-cards'],['Safety & risk','risk'],['Support','support']] as const;

export function DocsLayout({title,eyebrow,children}:{title:string;eyebrow:string;children:ReactNode}){
  return <div className="docs-page"><aside className="docs-sidebar"><Link href="/" className="docs-brand" aria-label="Return to Perks"><PerksWordmark/><ArrowUpRight size={15}/></Link><div className="docs-sidebar-intro"><span className="docs-kicker">Documentation</span><p>Everything you need to earn, claim, and spend rewards.</p></div><nav aria-label="Documentation"><span>Guides</span>{nav.map(([label,id])=><a href={`#${id}`} key={id}>{label}</a>)}</nav><div className="docs-sidebar-help"><span>Need a hand?</span><a href="mailto:hello@perks.fun">Email support <ExternalLink size={14}/></a></div></aside><main className="docs-main"><article className="docs-content"><p className="docs-kicker">{eyebrow}</p><h1>{title}</h1>{children}</article></main></div>;
}

export function DocsArticle(){return <DocsLayout eyebrow="Documentation" title="How Perks works"><section id="overview"><h3>A little something for active traders.</h3><p>Perks connects eligible on-chain activity with a reward balance you can use toward digital gift cards. Your balance and available cards are always shown before you choose an amount.</p><div className="docs-callout"><strong>The simple loop</strong><ol><li>Discover or launch a token.</li><li>Trade and build eligible rewards.</li><li>Choose a digital gift card when your balance is ready.</li></ol></div></section><section id="launching"><h3>Launching a token</h3><p>Use Create to prepare a token launch. Your connected wallet reviews and signs the transaction; Perks never signs for you. Creator-fee flows and network requirements are displayed before approval.</p></section><section id="rewards"><h3>Trading rewards</h3><p>Reward balances may include available, pending, reserved, and spent amounts. Pending rewards are still being reconciled. Only the available amount can be redeemed for a card.</p><ul><li><b>Available:</b> ready to use.</li><li><b>Awaiting collection:</b> earned but not finalized for redemption.</li><li><b>Reserved:</b> temporarily held for an in-progress purchase.</li></ul></section><section id="gift-cards"><h3>Gift cards</h3><p>Choose a country, card, and amount. Card availability, denominations, delivery rules, and redemption restrictions come from the gift-card provider and can vary by region.</p><p>After checkout, a completed card is delivered to the email address you confirm in the flow.</p></section><section id="risk"><h3>Safety & risk</h3><p>Crypto assets and token launches are risky. Prices move quickly, transactions can be irreversible, and rewards or card inventory may change. Verify wallet prompts, countries, and recipient email addresses before you approve anything.</p><p>This guide is informational only—not financial, legal, or tax advice.</p></section><section id="support"><h3>Support</h3><p>For a reward or gift-card issue, include your wallet address, the card brand, and any order identifier in an email to <a href="mailto:hello@perks.fun">hello@perks.fun</a>. Never send a seed phrase or private key.</p></section></DocsLayout>;}

export function LegalArticle({kind}:{kind:'privacy'|'terms'}){const privacy=kind==='privacy';return <DocsLayout eyebrow={privacy?'Legal':'Legal'} title={privacy?'Privacy Policy':'Terms of Service'}><p className="docs-effective">Effective September 20, 2026</p>{privacy?<><section id="overview"><h3>What this covers</h3><p>This policy explains how Perks handles information when you use the website, connect a wallet, browse cards, or contact support.</p></section><section><h3>Information we process</h3><p>We may process public wallet addresses, on-chain transaction information, card-order details, delivery email addresses, and technical information needed to operate and secure the service.</p></section><section><h3>How we use it</h3><p>We use this information to display rewards, process card orders, prevent abuse, provide support, and improve the product. We do not ask for your seed phrase or private keys.</p></section><section><h3>Service providers</h3><p>Gift-card fulfillment and infrastructure providers may process information needed to provide their part of the service. Their use of information is governed by their own terms and policies.</p></section><section><h3>Contact</h3><p>Questions about privacy can be sent to <a href="mailto:hello@perks.fun">hello@perks.fun</a>.</p></section></>:<><section id="overview"><h3>Using Perks</h3><p>By using Perks, you agree to use it lawfully and to review every wallet request, card selection, country restriction, and delivery email before confirming it.</p></section><section><h3>Wallets, tokens, and rewards</h3><p>You are responsible for your wallet and all transactions you approve. Token markets are volatile; rewards, eligibility, inventory, and redemption values may change or be unavailable.</p></section><section><h3>Gift cards</h3><p>Gift cards are provided by third-party issuers and providers. They may have country, redemption, expiration, and other restrictions. Once fulfilled or delivered, purchases may be final except where required by law.</p></section><section><h3>No advice or guarantees</h3><p>Perks is provided as-is. Nothing on the service is financial, investment, legal, or tax advice, and we do not guarantee any token, reward, card, or result.</p></section><section><h3>Changes and contact</h3><p>We may update these terms as the product evolves. Questions can be sent to <a href="mailto:hello@perks.fun">hello@perks.fun</a>.</p></section></>}</DocsLayout>;}
