import { Coins, Gift, Rocket, Wallet } from 'lucide-react';
import { DocsLayout } from './docs-shell';

export function DocsArticle() {
  return <DocsLayout eyebrow="Getting started" title="What is Perks?">
    <section id="overview" className="docs-overview"><h2 className="docs-visually-hidden">Overview</h2><p className="docs-lead">A little something for active traders. Perks brings token discovery, launches, and trading rewards together on Solana. Turn your available rewards into digital gift cards, all from one place.</p>
      <div className="docs-feature-grid">{[
        [Rocket, 'Discover and launch', 'Explore tokens or prepare a launch. Review the details and approve transactions in your own wallet.', 'launching'],
        [Coins, 'Follow your rewards', 'See available rewards and amounts awaiting collection, with a breakdown for each token.', 'rewards'],
        [Gift, 'Choose your perk', 'Browse digital gift cards by country, select an amount, and review the quote before checkout.', 'gift-cards'],
        [Wallet, 'Stay in control', 'Your wallet authorizes your transactions. Check every request before you approve it.', 'risk'],
      ].map(([Icon, title, description, id]) => { const FeatureIcon = Icon as typeof Coins; return <a className="docs-feature" href={`#${id}`} key={String(id)}><span className="docs-feature-icon"><FeatureIcon size={19} strokeWidth={1.7} /></span><h3>{String(title)}</h3><p>{String(description)}</p></a>; })}</div>
      <h3>Before you begin</h3><p>You’ll need a compatible Solana wallet to use wallet features. Keep enough SOL for any network fees shown in a transaction. Gift-card availability and redemption rules depend on the selected country and brand.</p>
    </section>
    <section id="quick-start"><h2>Quick start</h2><p>Follow the full path from connecting your wallet to choosing your first gift card.</p><ol className="docs-steps"><li><strong>Connect your wallet</strong><p>Open Perks and connect the wallet you use for your activity. Confirm that the displayed address matches the wallet you intended to use.</p></li><li><strong>Explore tokens and check your rewards</strong><p>Browse tokens from the home page. Open your wallet profile to see trading rewards and the per-token breakdown. Only finalized, eligible activity is reflected in rewards.</p></li><li><strong>Wait for an available balance</strong><p>Amounts awaiting collection are not yet spendable. The available balance is the amount you can use toward gift cards.</p></li><li><strong>Choose a card and review checkout</strong><p>Select the country, brand, and amount. Check the delivery email, redemption restrictions, and final quote before confirming.</p></li></ol></section>
    <section id="launching"><h2>Launching a token</h2><p>The Create flow prepares a token launch for your connected wallet. Launch availability and requirements are shown in the flow.</p><ol><li>Enter the token details and upload its image.</li><li>Review the prepared launch, any initial purchase, and the estimated debit.</li><li>Check the transaction in your wallet before signing.</li><li>Wait for confirmation before starting another attempt.</li></ol><div className="docs-callout"><strong>If confirmation is delayed</strong><p>A pending transaction is not the same as a failed transaction. Check its status and your wallet activity before retrying to avoid an unintended second action.</p></div></section>
    <section id="rewards"><h2>Trading rewards</h2><p>Your rewards view separates eligible rewards from the amount you can spend now. Balances are associated with the connected wallet, and the token breakdown helps you see where each amount comes from.</p><div className="docs-table-wrap"><table><caption>Understanding reward balances</caption><thead><tr><th>Balance</th><th>What it means</th></tr></thead><tbody><tr><td>Eligible rewards</td><td>Available rewards plus rewards awaiting collection.</td></tr><tr><td>Available to spend</td><td>Rewards ready to use toward a gift-card purchase.</td></tr><tr><td>Awaiting collection</td><td>Earned rewards whose fees have not yet been collected and finalized for spending.</td></tr><tr><td>Reserved</td><td>Rewards held for an in-progress purchase and unavailable for a second order.</td></tr><tr><td>Spent</td><td>Rewards already used for purchases.</td></tr></tbody></table></div><h3>Why a balance may not update immediately</h3><p>On-chain activity must be finalized and processed before it appears. Collection and order reconciliation can also affect when funds become available. If rewards are synchronizing, wait and check again; reconnecting a different wallet shows that wallet’s balances.</p></section>
    <section id="gift-cards"><h2>Gift cards</h2><p>Use <strong>Browse gift cards</strong> in your rewards view to explore the catalog. A brand’s presence in the catalog does not mean every denomination or country is supported.</p><h3>Review your selection</h3><ul><li><strong>Country:</strong> choose the region where the card will be redeemed.</li><li><strong>Amount:</strong> select an offered denomination or enter an amount within the displayed range.</li><li><strong>Quote:</strong> review the cost shown at checkout and your available balance.</li><li><strong>Delivery:</strong> confirm the recipient email and the brand’s redemption instructions.</li></ul><h3>After checkout</h3><p>Check the order status before making another purchase. A submitted or processing order is still in progress. Once fulfilled, follow the delivery and redemption instructions for that card. Keep any gift-card codes private.</p><div className="docs-callout"><strong>Missing a delivery email?</strong><p>Check the confirmed recipient address, spam folder, and order status. If the order is complete but delivery is missing, contact support with the order identifier and card brand.</p></div></section>
    <section id="risk"><h2>Safety &amp; risk</h2><p>Review the details of every wallet request and purchase. Token prices can change quickly, and an approved blockchain transaction may be irreversible.</p><ul><li>Never share your recovery phrase or private key, including with support.</li><li>Verify the token, amount, destination, and fees in wallet prompts.</li><li>Check gift-card country restrictions and issuer terms before purchase.</li><li>Do not treat a pending reward or an estimated quote as a completed payment.</li></ul><p>Read the <a href="/terms">Terms of Service</a> and <a href="/privacy">Privacy Policy</a> for the service’s terms and information handling.</p></section>
    <section id="faq"><h2>Frequently asked questions</h2><h3>Can I spend rewards awaiting collection?</h3><p>No. Only the available balance is ready for redemption. Eligible rewards can include amounts that are still awaiting collection.</p><h3>Why can’t I find a particular gift card?</h3><p>Inventory, denominations, and country availability vary by provider and brand. Check the selected country and the current catalog.</p><h3>What if I switch wallets?</h3><p>Your profile and rewards reflect the connected wallet address. Reconnect the original wallet to view its activity and balances.</p><h3>Should I retry an order that is processing?</h3><p>Check the existing order first. If its status remains unclear, contact support with the order identifier before placing another order.</p></section>
    <section id="support"><h2>Support</h2><p>Email <a href="mailto:hello@perks.fun">hello@perks.fun</a> with a short description of what happened and what you expected.</p><ul><li>Your public wallet address.</li><li>The order identifier and card brand, for a gift-card issue.</li><li>A transaction signature, if the issue concerns an on-chain action.</li><li>The error message and approximate time the issue occurred.</li></ul><p>Remove private information from screenshots. Never include a recovery phrase, private key, or gift-card redemption code.</p></section>
  </DocsLayout>;
}
