'use client';
import {useEffect,useState} from 'react';
import {api} from '@/lib/client';
type Amounts={eligibleLamports:string;availableLamports:string;pendingLamports:string;reservedLamports:string;spentLamports:string};
type Balance=Amounts&{syncing:boolean;rewardBps:number;tokens:(Amounts&{tokenMint:string;name:string;symbol:string})[]};
import {formatRewardSol as sol} from '@/lib/format-rewards';
export function WalletRewards({wallet}:{wallet:string}){
  const [balance,setBalance]=useState<Balance|null>(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;let timer:ReturnType<typeof setTimeout>;setBalance(null);
    async function refresh(){try{const result=await api<Balance>(`/api/rewards?wallet=${wallet}`);if(active){setBalance(result);setError('');}}catch{if(active)setError('Rewards are synchronizing. The last loaded balance may be outdated.');}finally{if(active)timer=setTimeout(refresh,15000);}}
    void refresh();return()=>{active=false;clearTimeout(timer);};
  },[wallet]);
  return <section className="profile-list" aria-label="Trading rewards">{(error||balance?.syncing)&&balance&&<p role="status" className="secure-note">Updating rewards… Showing your last verified balance.</p>}{!balance?<p className="profile-empty">Loading trading rewards…</p>:<>
    <div className="profile-row"><div><strong>Your trading rewards</strong><span>{balance.rewardBps/100}% of the actual creator fees generated by your eligible trades</span></div><div className="profile-row-value"><span>Eligible rewards</span><strong>{sol(balance.eligibleLamports)} SOL</strong></div></div>
    <p className="secure-note">Rewards from your verified trades, including fees awaiting collection. Selling your tokens does not remove earned rewards. Choose a gift card in My Perks to redeem.</p>
    {balance.tokens.map(token=><div className="profile-row" key={token.tokenMint}><div><strong>{token.name}</strong><span>{token.symbol} · {token.tokenMint.slice(0,4)}…{token.tokenMint.slice(-4)}</span></div><div className="profile-row-value"><strong>{sol(token.eligibleLamports)} SOL</strong><span>Eligible rewards</span></div></div>)}{!balance.tokens.length&&<p className="profile-empty">No finalized eligible trades yet.</p>}
  </>}</section>;
}
